#!/bin/bash
echo "🚀 Manual Purchase Agent - Railway Deployment Commands"
echo "====================================================="
echo ""
echo "I've prepared everything for deployment. The Railway CLI has limitations"
echo "for non-interactive deployments, but here's what you need to do:"
echo ""
echo "OPTION 1: Deploy via GitHub (Recommended)"
echo "----------------------------------------"
echo "1. Create a GitHub repository:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/manual-purchase-agent.git"
echo "   git push -u origin main"
echo ""
echo "2. Go to Railway dashboard:"
echo "   https://railway.com/project/2aaf026e-a3b5-49e9-9710-7df13ebec771"
echo ""
echo "3. Click 'New Service' → 'Deploy from GitHub repo'"
echo "4. Connect your GitHub account and select the repository"
echo "5. Railway will auto-deploy!"
echo ""
echo "OPTION 2: Deploy via Railway CLI (Manual steps)"
echo "-----------------------------------------------"
echo "1. In Railway dashboard, click 'New Service' → 'Empty Service'"
echo "2. Name it 'web'"
echo "3. Back in terminal, run:"
echo "   railway link --service web"
echo "   railway up"
echo ""
echo "ENVIRONMENT VARIABLES TO SET IN RAILWAY:"
echo "---------------------------------------"
echo "SERPAPI_KEY=7219228e748003a6e5394610456ef659f7c7884225b2df7fb0a890da61ad7f48"
echo "OPENAI_API_KEY=your_openai_api_key_here"
echo "SECRET_KEY=manual-purchase-agent-production-secret-key-2024"
echo "ENCRYPTION_KEY=z2KGjtN24oYD3KHkkr8bpKsjyxJAN2SgAfgILqWnO54="
echo "ENABLE_REAL_PURCHASES=false"
echo ""
echo "DATABASE:"
echo "---------"
echo "PostgreSQL is already added to your project!"
echo "Railway will automatically set DATABASE_URL"
echo ""
echo "📁 Files ready for deployment:"
echo "   ✅ Dockerfile"
echo "   ✅ requirements.txt"
echo "   ✅ Procfile"
echo "   ✅ railway.json"
echo "   ✅ railway.toml"
echo "   ✅ All source code"
echo ""
echo "Press Enter to open Railway dashboard..."
read -r
echo "Opening: https://railway.com/project/2aaf026e-a3b5-49e9-9710-7df13ebec771"